### ISSUE TITLE
dcat:downloadURL: Cardinality should be "0...n" instead of "1"

### ISSUE THREAD

**Issue by Juan-Juan-1** [opendata-swiss/dcat_ap_ch#182]
Properties: dcat:downloadURL

Classes: Distribution

Ist: In DCAT-AP-CH v1 the defined cardinality is "1", whereas in DCAT-AP it's "n"

Soll: Adapt to DCAT-AP and define cardinality as "n" in DCAT-AP-CH v2. Check possible implementation issues on opendata.swiss

**Comment by metaodi** [comment]
What is the purpose of providing multiple download URLs? Is this to provide mirror links and all of those are equal (i.e. provide the same file)?

**Comment by sabinem** [comment]
@metaodi and @Juan-Juan-1: See the discussion for this on DCAT-AP: https://github.com/SEMICeu/DCAT-AP/issues/93 regarding this topic.
 
The only use case mentioned there is a case where a file is too big for a download in one go and therefore might be split into several download urls. But since even DCAT-AP seems undecided about the cardinality, I agree with @metaodi that I don't see a need to change this on DCAT-AP CH now.

**Comment by Juan-Juan-1** [comment]
Mistake by construction of dcat-ap.ch. Cardinality is already correct 0…n
